language: generic
sudo: required
  - docker 

before_install:
  - docker build -t sanduljayathileka/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sanduljayathileka/react-test npm test

after_success:
  - docker build -t sanduljayathileka/multi-client ./client 
  - docker build -t sanduljayathileka/multi-nginx ./nginx
  - docker build -t sanduljayathileka/multi-server ./server
  - docker build -t sanduljayathileka/multi-worker ./worker

  # log in to the docker CLI 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # take those images and push them to docker hub 
  - docker push sanduljayathileka/multi-client
  - docker push sanduljayathileka/multi-nginx
  - docker push sanduljayathileka/multi-server
  - docker push sanduljayathileka/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-059663722075'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
